default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  host: localhost
  password: 123456

development:
  <<: *default
  host: localhost
  username: postgres
  database: kucina_development

test:
  <<: *default
  username: postgres
  password: 123456
  database: kucina_test

staging:
  <<: *default
  database: kucina_staging
  username: postgres
  password: 123456
  port: 5433
  host: localhost

production:
  <<: *default
  database: kucina_production
  username: <%= ENV['PRODUCTION_POSTGRES_USER'] %>
  password: <%= ENV['PRODUCTION_POSTGRES_PASS'] %>
  port: 5432
  host: <%= ENV['PRODUCTION_POSTGRES_HOST'] %>
